### ISSUE TITLE
部署开发环境后无法发送文字

### ISSUE THREAD

**Issue by skyjt** [elvinn/wedding-invitation#2]
写下祝福处无法输入文字

**Comment by elvinn** [comment]
控制台有报错吗？

**Comment by skyjt** [comment]
> 控制台有报错吗？

您README中的demo网站似乎也同样无法输入
无报错，仅有一个警告

> DevTools 无法加载 SourceMap: 无法加载 https://cdn.bootcdn.net/ajax/libs/moment.js/2.25.3/moment.min.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by elvinn** [comment]
使用的是什么浏览器呢？

**Comment by skyjt** [comment]
> 使用的是什么浏览器呢？

使用了 
EDGE( Chromium 版本 81.0.416.77 64位， windows 10 1903)
以及 
Safari( iOS 13.5 )
均有此问题

**Comment by skyjt** [comment]
对不起，我的问题，我搞错了
