### ISSUE TITLE
云函数的代码在哪里找呢？

### ISSUE THREAD

**Issue by yandycom** [elvinn/wedding-invitation#3]

**Comment by elvinn** [comment]
`functions` 目录下的代码为云函数代码，分别是获取弹幕、设置弹幕

**Comment by fngulee** [comment]
啊啊啊啊啊啊   老铁白屏 能看看吗

**Comment by fngulee** [comment]
&nbsp;我可以不可以直接在后台上传源文件而不是通过这种方式部署呢


&nbsp;有错误
&nbsp;555555555555


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Elvin Peng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 下午3:00
收件人:&nbsp;"elvinn/wedding-invitation"<wedding-invitation@noreply.github.com&gt;;
抄送:&nbsp;"′★__反骨. "<1361203818@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [elvinn/wedding-invitation] 云函数的代码在哪里找呢？ (#3)





 
Closed #3.

**Comment by fngulee** [comment]
&nbsp;老哥 这个字段在哪修改啊啊 啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Elvin Peng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 下午3:00
收件人:&nbsp;"elvinn/wedding-invitation"<wedding-invitation@noreply.github.com&gt;;
抄送:&nbsp;"′★__反骨. "<1361203818@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [elvinn/wedding-invitation] 云函数的代码在哪里找呢？ (#3)





 
Closed #3.
